### PR TITLE
Outdated copyright freaks me out

### PR DESCRIPTION
**Pull request by f3ath**
Hey! Thanks for your work. i3wm is my favorite, I have been using it for over 6 years.

### CODE REVIEW

**Comment by stapelberg** [comment]
Can you change it to 2009 only (i.e. no range) please? We’ve done this for all the other places a while ago.

**Comment by f3ath** [comment]
@stapelberg sure, done.

**Comment by stapelberg** [comment]
One more nitpick: can you squash the commits please? We’d like to keep our git history clean, i.e. one commit per logical change.

**Comment by f3ath** [comment]
@stapelberg here you are

**Pull request merged**
