### PR TITLE
fix swap monitor script

### PR DESCRIPTION
**Pull request by hylophile**
Without these changes, the script didn't work for me.
1. convert outputs into list as the filter object 'is not subscriptable'
2. add python after exec as it didn't work before (maybe my setup is wrong?)

### CODE REVIEW

**Comment by Airblader** [comment]
Perhaps you don't have /usr/bin/python2.7? That shebang is not ideal anyway, it should read

```
#!/usr/bin/env python2.7
```

Adding that explicit `python` should definitely not be necessary and is in fact wrong because it will default to python3 on many systems. I also assume that's why you needed the other change since you now work with python3. Can you try only changing the shebang as above and making sure you have python2.7 installed?

**Comment by Airblader** [comment]
That's a problem in your setup. The shebang should be used to correctly launch the script and for me it works with every script I call as well, so I see no reason why this should be different here. Since no other change is left I'm going to close this PR. We can certainly keep discussing the issue, though.

You could try and see what happens if you run the command through `/bin/sh -c` using the same environment as i3. Alternatively, you could try redirecting stdout and stderr to a file and see if any error is logged.

**Comment by hylophile** [comment]
I didn't exactly understand your instructions, but I did `chmod +x` on the file and now it's working... Woops. Still, thanks for taking the time to respond to such a minor issue!

**Comment by Airblader** [comment]
Yes, the executable bit must be set, of course. :-) No worries!

**Pull request closed without merging**
