### PR TITLE
Added link to i3status. Removed duplicate link to  Debugging.

### PR DESCRIPTION
**Pull request by snprajwal**
I have done the edits in docs/4.9 and the /docs folder since I was unsure which one is currently in use on the website. This is my first ever PR, so please excuse if I've done something incorrectly in the process.

### CODE REVIEW

**Comment by orestisfl** [comment]
I am not really sure about this change

1. i3status is not part of i3
2. debugging is useful to be visible for both developers and users since it is meant to be done by both

**Comment by Airblader** [comment]
@snprajwal First of all thanks for the suggestion and the PR!

> I have done the edits in docs/4.9 and the /docs folder since I was unsure which one is currently in use on the website.

Can you undo the changes to docs/4.9? Changing it in the current one should be good enough.

@orestisfl 

> i3status is not part of i3

That's true, but they are closely related. I know _I've_ had trouble finding the i3status page before as well. Of course we could completely reorganize the website, but I think we get a reasonable benefit for close to no effort here, so I'd go with it.

> debugging is useful to be visible for both developers and users since it is meant to be done by both

I agree, and I'd keep both for now as well.

**Comment by snprajwal** [comment]
@Airblader I have undone the changes to docs/4.9
@orestisfl @Airblader I simply thought that since both the "For users" and "For developers" links are displayed on the same page, it would be kinda redundant to have the exact same link twice. I am fairly confident devs will at least look at the links at the User section, which is why I left that link there :) Let me know if I have to undo the removal

**Comment by stapelberg** [comment]
Let’s leave the debugging link in both sections. It’s one of the most central documents, and when people are upset because things don’t work, we want them to find it no matter in which section they happen to be looking.

**Comment by stapelberg** [comment]
Thanks. Can you also properly revert your change to docs/4.9/index.html please? You’re still changing whitespace in this pull request.

**Comment by snprajwal** [comment]
@stapelberg it's done. Sorry, looks like my autoindenting did that.

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Thanks!

**Pull request merged**
